<?php
//
// File generated by Dolibarr installer 3.2.0 on 2012-07-31 21:25:17
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://crm.eneora.com';
$dolibarr_main_document_root='/homez.318/eneora/www/dolibarr/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/homez.318/eneora/www/dolibarr/htdocs/custom';
$dolibarr_main_data_root='/homez.318/eneora/www/dolibarr/documents';
$dolibarr_main_db_host='mysql51-36.bdb';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='eneoramod1';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='eneoramod1';
$dolibarr_main_db_pass='gWbzdCru';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='a687fa7216aa3b8deb1cae06b7d4fcb0';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>
