#!/bin/bash

git submodule add git@github.com:ATM-Consulting/dolibarr_module_abricot.git htdocs/custom/abricot
#git submodule add git@atmsrv1:store-advtargetemailing.git htdocs/custom/advtargetemailing
#git submodule add git@atmsrv1:store-agefodd.git htdocs/custom/agefodd
#git submodule add git@atmsrv1:store-allscreens.git htdocs/custom/allscreens
#git submodule add git@atmsrv1:atm-theme.git htdocs/custom/atmtheme
git submodule add git@github.com:ATM-Consulting/dolibarr_module_attachementsaslink.git htdocs/custom/attachementsaslink
#git submodule add git@atmsrv1:doli-bankimport.git htdocs/custom/bankimport
git submodule add git@github.com:ATM-Consulting/dolibarr_module_breadcrumb.git htdocs/custom/breadcrumb
#git submodule add git@atmsrv1:doli-cli-atm.git htdocs/custom/cliatm
#git submodule add git@atmsrv1:store-concatpdf.git htdocs/custom/concatpdf
git submodule add git@github.com:ATM-Consulting/dolibarr_module_contactdefault.git htdocs/custom/contactdefault
#git submodule add git@atmsrv1:store-contratabonnement.git htdocs/custom/contratabonnement
git submodule add git@github.com:ATM-Consulting/dolibarr_module_doc2project.git htdocs/custom/doc2project
git submodule add git@github.com:ATM-Consulting/dolibarr_module_docpreview.git htdocs/custom/docpreview
git submodule add git@git.framasoft.org:ATM-Consulting/Dropcloud.git htdocs/custom/dropcloud
#git submodule add git@atmsrv1:doli-export-compta.git htdocs/custom/exportcompta
git submodule add git@github.com:ATM-Consulting/dolibarr_module_fullcalendar.git htdocs/custom/fullcalendar
#git submodule add git@atmsrv1:store-google.git htdocs/custom/google
git submodule add git@github.com:ATM-Consulting/dolibarr_module_googlecontactsync.git htdocs/custom/googlecontactsync
#git submodule add git@atmsrv1:doli-gpec.git htdocs/custom/gpec
git submodule add git@github.com:ATM-Consulting/dolibarr_module_lostintranslation.git htdocs/custom/lostintranslation
#git submodule add git@atmsrv1:store-mailchimp.git htdocs/custom/mailchimp
#git submodule add git@atmsrv1:doli-mantis-connector.git htdocs/custom/mantis
#git submodule add git@atmsrv1:multicompany.git htdocs/custom/multicompany
#git submodule add git@atmsrv1:store-multismtp.git htdocs/custom/multismtp
#git submodule add git@atmsrv1:doli-ndfp-rh.git htdocs/custom/ndfp
git submodule add git@github.com:ATM-Consulting/dolibarr_module_odtdoc.git htdocs/custom/odtdocs
git submodule add git@github.com:ATM-Consulting/dolibarr_module_postit.git htdocs/custom/postit
git submodule add git@github.com:ATM-Consulting/dolibarr_module_propalehistory.git htdocs/custom/propalehistory
git submodule add git@github.com:ATM-Consulting/dolibarr_module_query.git htdocs/custom/query
git submodule add git@github.com:ATM-Consulting/dolibarr_module_recouvrement.git htdocs/custom/recouvrement
git submodule add git@github.com:ATM-Consulting/dolibarr_module_recurence.git htdocs/custom/recurrence
git submodule add git@github.com:ATM-Consulting/dolibarr_module_related.git htdocs/custom/related
git submodule add git@github.com:ATM-Consulting/dolibarr_module_rememberme.git htdocs/custom/rememberme
git submodule add git@github.com:ATM-Consulting/dolibarr_module_scrollto.git htdocs/custom/scrollto
git submodule add git@github.com:ATM-Consulting/dolibarr_module_scrumboard.git htdocs/custom/scrumboard
git submodule add git@github.com:ATM-Consulting/dolibarr_module_searcheverywhere.git htdocs/custom/searcheverywhere
#git submodule add git@atmsrv1:doli-sepa.git htdocs/custom/sepa
git submodule add git@github.com:ATM-Consulting/dolibarr_module_serverobserver.git htdocs/custom/serverobserver
#git submodule add git@atmsrv1:doli-sig.git htdocs/custom/sig
git submodule add git@github.com:ATM-Consulting/dolibarr_module_split.git htdocs/custom/split
git submodule add git@github.com:ATM-Consulting/dolibarr_module_subtotal.git htdocs/custom/subtotal
git submodule add git@github.com:ATM-Consulting/dolibarr_module_syncmailagenda.git htdocs/custom/syncmailagenda
git submodule add git@github.com:ATM-Consulting/dolibarr_module_upbuttons.git htdocs/custom/upbuttons
#git submodule add git@atmsrv1:store-zenfusionmaps.git htdocs/custom/zenfusionmaps
git submodule add git@github.com:ATM-Consulting/dolibarr_module_abricot.git htdocs/custom/abricot
#git submodule add git@atmsrv1:store-advtargetemailing.git htdocs/custom/advtargetemailing
#git submodule add git@atmsrv1:store-agefodd.git htdocs/custom/agefodd
#git submodule add git@atmsrv1:store-allscreens.git htdocs/custom/allscreens
#git submodule add git@atmsrv1:atm-theme.git htdocs/custom/atmtheme
git submodule add git@github.com:ATM-Consulting/dolibarr_module_attachementsaslink.git htdocs/custom/attachementsaslink
#git submodule add git@atmsrv1:doli-bankimport.git htdocs/custom/bankimport
git submodule add git@github.com:ATM-Consulting/dolibarr_module_breadcrumb.git htdocs/custom/breadcrumb
#git submodule add git@atmsrv1:doli-cli-atm.git htdocs/custom/cliatm
#git submodule add git@atmsrv1:store-concatpdf.git htdocs/custom/concatpdf
git submodule add git@github.com:ATM-Consulting/dolibarr_module_contactdefault.git htdocs/custom/contactdefault
#git submodule add git@atmsrv1:store-contratabonnement.git htdocs/custom/contratabonnement
git submodule add git@github.com:ATM-Consulting/dolibarr_module_doc2project.git htdocs/custom/doc2project
git submodule add git@github.com:ATM-Consulting/dolibarr_module_docpreview.git htdocs/custom/docpreview
git submodule add git@git.framasoft.org:ATM-Consulting/Dropcloud.git htdocs/custom/dropcloud
#git submodule add git@atmsrv1:doli-export-compta.git htdocs/custom/exportcompta
git submodule add git@github.com:ATM-Consulting/dolibarr_module_fullcalendar.git htdocs/custom/fullcalendar
#git submodule add git@atmsrv1:store-google.git htdocs/custom/google
git submodule add git@github.com:ATM-Consulting/dolibarr_module_googlecontactsync.git htdocs/custom/googlecontactsync
#git submodule add git@atmsrv1:doli-gpec.git htdocs/custom/gpec
git submodule add git@github.com:ATM-Consulting/dolibarr_module_lostintranslation.git htdocs/custom/lostintranslation
#git submodule add git@atmsrv1:store-mailchimp.git htdocs/custom/mailchimp
#git submodule add git@atmsrv1:doli-mantis-connector.git htdocs/custom/mantis
#git submodule add git@atmsrv1:multicompany.git htdocs/custom/multicompany
#git submodule add git@atmsrv1:store-multismtp.git htdocs/custom/multismtp
#git submodule add git@atmsrv1:doli-ndfp-rh.git htdocs/custom/ndfp
git submodule add git@github.com:ATM-Consulting/dolibarr_module_odtdoc.git htdocs/custom/odtdocs
git submodule add git@github.com:ATM-Consulting/dolibarr_module_postit.git htdocs/custom/postit
git submodule add git@github.com:ATM-Consulting/dolibarr_module_propalehistory.git htdocs/custom/propalehistory
git submodule add git@github.com:ATM-Consulting/dolibarr_module_query.git htdocs/custom/query
git submodule add git@github.com:ATM-Consulting/dolibarr_module_recouvrement.git htdocs/custom/recouvrement
git submodule add git@github.com:ATM-Consulting/dolibarr_module_recurence.git htdocs/custom/recurrence
git submodule add git@github.com:ATM-Consulting/dolibarr_module_related.git htdocs/custom/related
git submodule add git@github.com:ATM-Consulting/dolibarr_module_rememberme.git htdocs/custom/rememberme
git submodule add git@github.com:ATM-Consulting/dolibarr_module_scrollto.git htdocs/custom/scrollto
git submodule add git@github.com:ATM-Consulting/dolibarr_module_scrumboard.git htdocs/custom/scrumboard
git submodule add git@github.com:ATM-Consulting/dolibarr_module_searcheverywhere.git htdocs/custom/searcheverywhere
#git submodule add git@atmsrv1:doli-sepa.git htdocs/custom/sepa
git submodule add git@github.com:ATM-Consulting/dolibarr_module_serverobserver.git htdocs/custom/serverobserver
#git submodule add git@atmsrv1:doli-sig.git htdocs/custom/sig
git submodule add git@github.com:ATM-Consulting/dolibarr_module_split.git htdocs/custom/split
git submodule add git@github.com:ATM-Consulting/dolibarr_module_subtotal.git htdocs/custom/subtotal
git submodule add git@github.com:ATM-Consulting/dolibarr_module_syncmailagenda.git htdocs/custom/syncmailagenda
git submodule add git@github.com:ATM-Consulting/dolibarr_module_upbuttons.git htdocs/custom/upbuttons
#git submodule add git@atmsrv1:store-zenfusionmaps.git htdocs/custom/zenfusionmaps
#git submodule add git@atmsrv1:store-zenfusionoauth.git htdocs/custom/zenfusionoauth
#git submodule add git@atmsrv1:store-zenfusionoauth.git htdocs/custom/zenfusionoauth


